
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - catapult.thetechnick.ninja
  resources:
  - remoteapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catapult.thetechnick.ninja
  resources:
  - remoteapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - catapult.thetechnick.ninja
  resources:
  - remoteclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catapult.thetechnick.ninja
  resources:
  - remoteclusters/status
  verbs:
  - get
  - patch
  - update
