# permissions for end users to view remoteclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remotecluster-viewer-role
rules:
- apiGroups:
  - catapult.thetechnick.ninja
  resources:
  - remoteclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catapult.thetechnick.ninja
  resources:
  - remoteclusters/status
  verbs:
  - get
