# permissions for end users to edit remoteclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remotecluster-editor-role
rules:
- apiGroups:
  - catapult.thetechnick.ninja
  resources:
  - remoteclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catapult.thetechnick.ninja
  resources:
  - remoteclusters/status
  verbs:
  - get
